version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - "5000:5000"
    environment:
      FLASK_DB_HOST: ""
      DB_USER: scratch
      DB_PASSWD: Sc1thscr@tch
      DB_HOST: db
      DB_PORT: "5432"
      FLASK_ENV: "production"

    depends_on:
      - db
    restart: on-failure

  db:
    build:
      context: .
      dockerfile: postgres.Dockerfile
    ports:
      - "5549:5432"
    environment:
      POSTGRES_USER: scratch
      POSTGRES_PASSWORD: Sc1thscr@tch

