apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
  matchLabels:
    app: {{ include "backend.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "backend.fullname" . }}
    spec:
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        name: {{ include "backend.fullname" . }}
        ports:
          - name: http
            containerPort: 5000
        env:
          - name: APP_VALUE
          valueFrom:
            configMapKeyRef:
              name: backend-config
          - name: APP_VALUE_2
          valueFrom:
            configMapKeyRef:
              name: backend-config
        envFrom:
        - configMapRef:
            name: {{ include "backend.fullname" . }}-configmap
