apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ include "database.fullname" . }}
  name: {{ include "database.fullname" . }}
spec:
  ports:
    - name: default
      port: 5432
      targetPort: 5432
  selector:
    app: {{ include "database.fullname" . }}
