apiVersion: v1
kind: Secret
metadata:
  name: {{ include "database.fullname" . }}-secret
data:
  POSTGRES_USER: {{ .Values.secret.mongodb_username | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.secret.mongodb_password | b64enc | quote }}